name: ARM

on:
  push:
    branches:
      - main
      - ci-sandbox
  pull_request:
    branches:
      - "**"

permissions:
  contents: read

env:
  ccache_basedir: ${{ github.workspace }}
  ccache_dir: "${{ github.workspace }}/.ccache"
  ccache_compilercheck: content
  ccache_compress: "true"
  ccache_compresslevel: "9"
  ccache_maxsize: 200M
  ccache_cmake: -DCMAKE_CXX_COMPILER_LAUNCHER=ccache -DCMAKE_C_COMPILER_LAUNCHER=ccache
  ndk_version: r27c
  ndk: "${{ github.workspace }}/android-ndk-r27c"
  abi: arm64-v8a
  android_platform: 28

jobs:
  ubuntu:
    name: "arm64-v8a cross-compile via Android NDK"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          submodules: recursive

      - name: Install prerequisites
        run: |
          wget -c --quiet "https://dl.google.com/android/repository/android-ndk-${{ env.ndk_version }}-linux.zip"
          unzip -qq "android-ndk-${{ env.ndk_version }}-linux.zip"
          sudo apt-get update
          sudo apt-get -y install ccache cmake

      - name: Generate ccache_vars
        shell: bash
        id: ccache_vars
        run: |
          echo "hash=${{ env.ccache_compilercheck }}" >> "$GITHUB_OUTPUT"
          echo "timestamp=$(date '+%Y-%m-%dT%H.%M.%S')" >> "$GITHUB_OUTPUT"

      - name: Cache build with ccache
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: ${{ env.ccache_dir }}
          key: ccache-arm-${{ steps.ccache_vars.outputs.hash }}-${{ github.ref }}-${{ steps.ccache_vars.outputs.timestamp }}
          restore-keys: |
            ccache-arm-${{ steps.ccache_vars.outputs.hash }}-${{ github.ref }}
            ccache-arm-${{ steps.ccache_vars.outputs.hash }}
            ccache-arm-

      - name: ccache environment setup
        run: |
          echo "CCACHE_COMPILER_CHECK=${{ env.ccache_compilercheck }}" >> "$GITHUB_ENV"
          echo "CCACHE_BASEDIR=${{ env.ccache_basedir }}" >> "$GITHUB_ENV"
          echo "CCACHE_COMPRESS=${{ env.ccache_compress }}" >> "$GITHUB_ENV"
          echo "CCACHE_COMPRESSLEVEL=${{ env.ccache_compresslevel }}" >> "$GITHUB_ENV"
          echo "CCACHE_DIR=${{ env.ccache_dir }}" >> "$GITHUB_ENV"
          echo "CCACHE_MAXSIZE=${{ env.ccache_maxsize }}" >> "$GITHUB_ENV"

      - name: ccache prolog
        run: |
          ccache -s
          ccache -z

      - name: Generate buildfiles for bergamot-translator on android via cmake
        run: |
          mkdir -p build
          cd build
          NDK=${{ env.ndk }}
          cmake -L \
              -DCMAKE_BUILD_TYPE=Release \
              -DCMAKE_POLICY_VERSION_MINIMUM=3.5 \
              -DCMAKE_TOOLCHAIN_FILE=$NDK/build/cmake/android.toolchain.cmake \
              -DANDROID_ABI=${{ env.abi }} \
              -DANDROID_PLATFORM=android-${{ env.android_platform }} \
              -DANDROID_STL=c++_static \
              -DCOMPILE_CUDA=off \
              -DCOMPILE_CPU=on \
              -DCMAKE_HAVE_THREADS_LIBRARY=1 \
              -DCMAKE_USE_WIN32_THREADS_INIT=0 \
              -DCMAKE_USE_PTHREADS_INIT=1 \
              -DTHREADS_PREFER_PTHREAD_FLAG=ON \
              -DBUILD_ARCH=armv8-a \
              -DSSPLIT_USE_INTERNAL_PCRE2=ON \
              ${{ env.ccache_cmake }} \
              ..

      - name: Build bergamot-translator for android
        working-directory: build
        run: make -j2

      - name: ccache epilog
        run: ccache -s

      - name: Upload artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: bergamot-arm64-v8a
          path: ${{ github.workspace }}/build/app/bergamot
