name: "Build"

on:
  push:
    branches:
      - main
      - ci-sandbox
    tags:
      - "v*.*.*"
  pull_request:
    branches:
      - "**"

permissions:
  contents: read

env:
  emsdk_version: "3.1.8"
  ccache_basedir: ${{ github.workspace }}
  ccache_dir: "${{ github.workspace }}/.ccache"
  ccache_compilercheck: content
  ccache_compress: "true"
  ccache_compresslevel: "9"
  ccache_maxsize: 200M
  ccache_cmake: -DCMAKE_CXX_COMPILER_LAUNCHER=ccache -DCMAKE_C_COMPILER_LAUNCHER=ccache

jobs:
  build-wheels:
    name: "cibuildwheel / ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-13]

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          submodules: recursive

      - name: Generate ccache_vars
        shell: bash
        id: ccache_vars
        run: |
          echo "hash=${{ env.ccache_compilercheck }}" >> "$GITHUB_OUTPUT"
          echo "timestamp=$(date '+%Y-%m-%dT%H.%M.%S')" >> "$GITHUB_OUTPUT"

      - name: Cache build with ccache
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: ${{ env.ccache_dir }}
          key: ccache-cibuildwheel-${{ matrix.os }}-${{ steps.ccache_vars.outputs.hash }}-${{ github.ref }}-${{ steps.ccache_vars.outputs.timestamp }}
          restore-keys: |
            ccache-cibuildwheel-${{ matrix.os }}-${{ steps.ccache_vars.outputs.hash }}-${{ github.ref }}
            ccache-cibuildwheel-${{ matrix.os }}-${{ steps.ccache_vars.outputs.hash }}
            ccache-cibuildwheel-${{ matrix.os }}

      - name: ccache environment setup
        run: |
          mkdir -p ${{ env.ccache_dir }}

      - name: Apply MacOS patch
        if: startsWith(runner.os, 'mac')
        run: patch -p1 < patches/01-marian-fstream-for-macos.patch

      - name: Build wheels
        uses: pypa/cibuildwheel@cfbec0988a9c12de5a84206e42aa17442af10d44 # v4.2.1
        env:
          CIBW_MANYLINUX_X86_64_IMAGE: manylinux_2_28
          CIBW_ENVIRONMENT_LINUX: |
            BUILD_ARCH=core-avx-i
            USE_CCACHE=1
            CCACHE_COMPILER_CHECK=${{ env.ccache_compilercheck }}
            CCACHE_COMPRESS=${{ env.ccache_compress }}
            CCACHE_COMPRESSLEVEL=${{ env.ccache_compresslevel }}
            CCACHE_MAXSIZE=${{ env.ccache_maxsize }}
            PYTHON_LOCAL_VERSION_IDENTIFIER=${{ env.PYTHON_LOCAL_VERSION_IDENTIFIER }}
            CCACHE_DIR=/host/${{ env.ccache_dir }}
            CCACHE_BASEDIR=/host/${{ env.ccache_basedir }}
            CMAKE_ARGS=-DBLA_VENDOR=OpenBLAS -DBLAS_INCLUDE_DIR=/usr/include/openblas -DCBLAS_LIBRARIES=/usr/lib64/libopenblas.so -DCBLAS_INCLUDE_DIR=/usr/include/openblas
          CIBW_ENVIRONMENT_MACOS: |
            BUILD_ARCH=core-avx-i
            USE_CCACHE=1
            CCACHE_COMPILER_CHECK=${{ env.ccache_compilercheck }}
            CCACHE_COMPRESS=${{ env.ccache_compress }}
            CCACHE_COMPRESSLEVEL=${{ env.ccache_compresslevel }}
            CCACHE_MAXSIZE=${{ env.ccache_maxsize }}
            PYTHON_LOCAL_VERSION_IDENTIFIER=${{ env.PYTHON_LOCAL_VERSION_IDENTIFIER }}
            CCACHE_DIR=${{ env.ccache_dir }}
            CCACHE_BASEDIR=${{ env.ccache_basedir }}
            MACOSX_DEPLOYMENT_TARGET=10.9
            CMAKE_ARGS=-DBLA_VENDOR=OpenBLAS -DCBLAS_LIBRARIES=/usr/local/opt/openblas/lib/libopenblas.dylib -DCBLAS_INCLUDE_DIR=/usr/local/opt/openblas/include
          CIBW_BEFORE_BUILD_LINUX: |
            yum install -y ccache
            yum --enablerepo=powertools install -y openblas-devel
            chmod -R a+rwx /host/${{ env.ccache_dir }}
            ccache -s
            ccache -z
          CIBW_BEFORE_BUILD_MACOS: |
            brew install openblas protobuf ccache boost pybind11
            chmod -R a+rwx ${{ env.ccache_dir }}
            ccache -s
            ccache -z
          CIBW_BUILD: "cp39-manylinux_x86_64 cp310-manylinux_x86_64 cp311-manylinux_x86_64 cp312-manylinux_x86_64 cp313-manylinux_x86_64 cp39-macosx_x86_64 cp310-macosx_x86_64 cp311-macosx_x86_64 cp312-macosx_x86_64 cp313-macosx_x86_64"
          CIBW_BEFORE_TEST: ccache -s
          CIBW_TEST_COMMAND: |
            python3 -m bergamot download -m en-de-tiny
            python3 -m bergamot download -m de-en-tiny
            python3 -m bergamot ls
            python3 -m bergamot download -m eng-fin-tiny -r opus
            python3 -m bergamot ls -r opus
            python3 -m bergamot translate --model en-de-tiny <<< "Hello World"
            python3 -m bergamot translate --model en-de-tiny de-en-tiny <<< "Hello World"
            python3 -m bergamot translate --model eng-fin-tiny --repository opus <<< "Hello World"

      - name: Upload wheels
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: wheels
          path: ./wheelhouse/*.whl

  upload-wheels:
    name: "Upload wheels to PyPI"
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    needs: [build-wheels]
    permissions:
      contents: read
      id-token: write
    environment: release
    steps:
      - name: Download wheels
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: wheels

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@a892a5a61159132606e93a2fa6f4358831b04d26 # v1.14.2

  build-wasm:
    name: "emscripten"
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          submodules: recursive

      - name: Set ccache environment for emcc
        run: |
          echo "CCACHE_COMPILER_CHECK=mtime" >> "$GITHUB_ENV"
          echo "CCACHE_BASEDIR=${{ env.ccache_basedir }}" >> "$GITHUB_ENV"
          echo "CCACHE_COMPRESS=${{ env.ccache_compress }}" >> "$GITHUB_ENV"
          echo "CCACHE_COMPRESSLEVEL=${{ env.ccache_compresslevel }}" >> "$GITHUB_ENV"
          echo "CCACHE_DIR=${{ env.ccache_dir }}" >> "$GITHUB_ENV"
          echo "CCACHE_MAXSIZE=${{ env.ccache_maxsize }}" >> "$GITHUB_ENV"
          echo "EM_COMPILER_WRAPPER=ccache" >> "$GITHUB_ENV"

      - name: Obtain emsdk sources
        run: git clone --depth 1 https://github.com/emscripten-core/emsdk.git

      - name: Generate ccache_vars
        shell: bash
        id: ccache_vars
        run: |
          echo "hash=${{ env.ccache_compilercheck }}" >> "$GITHUB_OUTPUT"
          echo "timestamp=$(date '+%Y-%m-%dT%H.%M.%S')" >> "$GITHUB_OUTPUT"

      - name: Cache build with ccache
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: |
            ${{ env.ccache_dir }}
            ${{ github.workspace }}/emsdk/ccache/git-emscripten_64bit/
          key: ccache-${{ github.job }}-${{ env.emsdk_version }}-${{ steps.ccache_vars.outputs.hash }}-${{ github.ref }}-${{ steps.ccache_vars.outputs.timestamp }}
          restore-keys: |
            ccache-${{ github.job }}-${{ env.emsdk_version }}-${{ steps.ccache_vars.outputs.hash }}-${{ github.ref }}
            ccache-${{ github.job }}-${{ env.emsdk_version }}-${{ steps.ccache_vars.outputs.hash }}
            ccache-${{ github.job }}-${{ env.emsdk_version }}

      - name: Setup Emscripten toolchain
        run: |
          (cd emsdk && ./emsdk install ${{ env.emsdk_version }} ccache-git-emscripten-64bit)
          (cd emsdk && ./emsdk activate ${{ env.emsdk_version }} ccache-git-emscripten-64bit)
          touch -m -d '1 Jan 2021 12:00' emsdk/.emscripten
          eval $(./emsdk/emsdk construct_env \
              | sed 's/export PATH=\(.*\);/echo \1 >> $GITHUB_PATH;/' \
              | sed 's/export \(.*\);/echo \1 >> $GITHUB_ENV;/' );
          echo "${{ github.workspace }}/emsdk/ccache/git-emscripten_64bit/bin" >> "$GITHUB_PATH"

      - name: Verify Emscripten setup
        run: |
          emcc --version
          emcmake cmake --version
          emmake make --version

      - name: ccache prolog
        run: |
          ccache -s
          ccache -z

      - name: Configure builds
        run: |
          mkdir -p build-wasm
          cd build-wasm
          emcmake cmake -DCOMPILE_WASM=on -DCMAKE_POLICY_VERSION_MINIMUM=3.5 ..

      - name: Compile
        working-directory: build-wasm
        run: emmake make -j2

      - name: ccache epilog
        run: ccache -s

      - name: Import GEMM library from a separate wasm module
        working-directory: build-wasm
        run: bash ../wasm/patch-artifacts-import-gemm-module.sh

      - name: Setup nodejs
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: 22

      - name: Test run
        working-directory: wasm
        run: |
          cp ../build-wasm/bergamot-translator-worker.{js,wasm} ./
          npm install jsdom@24.0.0
          node --unhandled-rejections=strict node-test.js

      - name: Upload wasm artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: wasm-artefacts
          if-no-files-found: error
          path: |
            ${{ github.workspace }}/build-wasm/bergamot-translator-worker.js
            ${{ github.workspace }}/build-wasm/bergamot-translator-worker.wasm

  upload-wasm:
    name: "Upload node package to NPM"
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    needs: [build-wasm]
    permissions:
      contents: read
      id-token: write
    environment: release
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: wasm-artefacts
          path: wasm/module/worker

      - name: Setup nodejs
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: 22
          registry-url: "https://registry.npmjs.org"

      - name: Install package dependencies
        working-directory: wasm/module
        run: npm install --ignore-scripts

      - name: Publish to npm
        working-directory: wasm/module
        run: npm publish --access public --provenance --ignore-scripts
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  release-latest:
    name: Release Latest Build
    runs-on: ubuntu-latest
    needs: [build-wheels, build-wasm]
    if: github.ref == 'refs/heads/main'
    permissions:
      contents: write
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1

      - name: Publish latest pre-release
        uses: softprops/action-gh-release@efb35369e0ad2afab669f228072c1b0d510eae64 # v3.0.3
        with:
          name: "Latest Build"
          tag_name: latest
          prerelease: true
          files: |
            wheels/*.whl
            wasm-artefacts/bergamot-translator-worker.js
            wasm-artefacts/bergamot-translator-worker.wasm

  release-version:
    name: Release version
    runs-on: ubuntu-latest
    needs: [build-wheels, build-wasm]
    if: startsWith(github.ref, 'refs/tags/v')
    permissions:
      contents: write
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1

      - name: Publish release
        uses: softprops/action-gh-release@efb35369e0ad2afab669f228072c1b0d510eae64 # v3.0.3
        with:
          name: "${{ github.ref_name }}"
          tag_name: "${{ github.ref_name }}"
          files: |
            wheels/*.whl
            wasm-artefacts/bergamot-translator-worker.js
            wasm-artefacts/bergamot-translator-worker.wasm

  python-checks:
    name: "formatting and typechecks"
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          submodules: recursive

      - name: Set up Python
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python3 -m pip install black isort pytype
          python3 -m pip install requests 'urllib3<2' pyyaml 'platformdirs'

      - name: Formatting checks
        run: |
          python3 -m black --diff --check bindings/python/ setup.py doc/conf.py
          python3 -m isort --profile black --diff --check bindings/python setup.py doc/conf.py

      - name: Static typing checks
        run: python3 -m pytype bindings/python

  docs:
    name: Build and deploy documentation
    runs-on: ubuntu-latest
    needs: [build-wheels]
    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          submodules: recursive

      - name: Download wheels
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: wheels

      - name: Set BERGAMOT_VERSION for docs
        run: echo "${{ github.ref_name }}" > BERGAMOT_VERSION

      - name: Set up Doxygen
        run: sudo apt-get update && sudo apt-get install -y doxygen

      - name: Set up Python
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: "3.11"

      - name: Set up dependency cache
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('doc/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        working-directory: ./doc
        run: |
          python3 -m pip install -r requirements.txt
          python3 -m pip install --find-links=${{ github.workspace }}/wheels quad4-bergamot

      - name: Build documentation
        working-directory: ./doc
        run: sphinx-build -b html ./ build/

      - name: Upload documentation
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        if: github.event_name == 'pull_request'
        with:
          name: api-docs
          path: ./doc/build/
          if-no-files-found: error

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@fc324d3547104276b827a68afc52ff2a11cc49c9 # v5.0.0
        if: github.event_name == 'push'
        with:
          path: ./doc/build/

      - name: Deploy to GitHub Pages
        if: github.event_name == 'push'
        id: deployment
        uses: actions/deploy-pages@368f82528645a54fb793d4d04e342629a3f51346 # v5.0.1
