name: Release

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    uses: ./.github/workflows/build.yml
    permissions:
      contents: write
      id-token: write

  publish-github-package:
    name: Publish npm package to GitHub Packages
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/publish-github-packages.yml
    with:
      tag: ${{ github.ref_name }}
