name: Windows

on:
  push:
    branches: [main, ci-sandbox]
  pull_request:
    branches: ["**"]

permissions:
  contents: read

env:
  MKL_URL: "https://data.statmt.org/romang/marian-regression-tests/ci/mkl-2020.1-windows-static.zip"
  CCACHE_BASEDIR: "${{ github.workspace }}"
  CCACHE_DIR: "${{ github.workspace }}\\ccache"
  CCACHE_COMPILERCHECK: content
  CCACHE_COMPRESS: "true"
  CCACHE_COMPRESSLEVEL: "9"
  CCACHE_MAXSIZE: 200M

jobs:
  build-windows:
    strategy:
      matrix:
        include:
          - name: "Windows CPU-only"
            identifier: "windows-x64"

    runs-on: windows-2022
    name: ${{ matrix.name }}

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          submodules: recursive

      - name: Install ccache
        run: choco install ccache --no-progress

      - name: Generate ccache_vars
        shell: pwsh
        id: ccache_vars
        run: |
          $ts = Get-Date -Format "yyyy-MM-ddTHH.mm.ss"
          "timestamp=$ts" | Out-File -FilePath $env:GITHUB_OUTPUT -Append -Encoding utf8
          "hash=${{ env.CCACHE_COMPILERCHECK }}" | Out-File -FilePath $env:GITHUB_OUTPUT -Append -Encoding utf8

      - name: Cache build with ccache
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: ${{ env.CCACHE_DIR }}
          key: ccache-${{ matrix.identifier }}-${{ steps.ccache_vars.outputs.hash }}-${{ github.ref }}-${{ steps.ccache_vars.outputs.timestamp }}
          restore-keys: |
            ccache-${{ matrix.identifier }}-${{ steps.ccache_vars.outputs.hash }}-${{ github.ref }}
            ccache-${{ matrix.identifier }}-${{ steps.ccache_vars.outputs.hash }}
            ccache-${{ matrix.identifier }}

      - name: ccache prolog
        run: |
          ccache.exe -sv
          ccache.exe -z

      - name: Download MKL
        shell: powershell
        run: |
          C:\msys64\usr\bin\wget.exe -nv ${{ env.MKL_URL }} -O mkl.zip
          Expand-Archive -Force mkl.zip ${{ github.workspace }}\mkl
          echo "MKLROOT=${{ github.workspace }}\mkl" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

      - name: Disable debug vcpkg build
        shell: powershell
        working-directory: C:\vcpkg\triplets
        run: |
          $PSDefaultParameterValues['Out-File:Encoding'] = 'utf8'
          echo "set(VCPKG_BUILD_TYPE release)" | Tee-Object -FilePath x64-windows-static.cmake -Append
          echo "set(VCPKG_BUILD_TYPE release)" | Tee-Object -FilePath x64-windows.cmake -Append
          cat x64-windows-static.cmake
          cat x64-windows.cmake

      - name: Install dependencies with vcpkg
        working-directory: C:\vcpkg
        shell: powershell
        run: |
          $Env:VCPKG_BUILD_TYPE = 'release'
          $Env:VCPKG_DEFAULT_TRIPLET = 'x64-windows-static'
          .\vcpkg install protobuf:x64-windows-static pcre2:x64-windows-static
          .\vcpkg upgrade --no-dry-run

      - name: Create build environment
        run: cmake -E make_directory ${{ github.workspace }}/build

      - name: Configure
        working-directory: ${{ github.workspace }}/build
        shell: powershell
        run: |
          cmake .. -DCMAKE_BUILD_TYPE=Release -DUSE_STATIC_LIBS=ON -DVCPKG_TARGET_TRIPLET='x64-windows-static' `
                -DCMAKE_TOOLCHAIN_FILE="C:/vcpkg/scripts/buildsystems/vcpkg.cmake" `
                -DCMAKE_CXX_COMPILER_LAUNCHER=ccache `
                -DCMAKE_C_COMPILER_LAUNCHER=ccache

      - name: Build
        working-directory: ${{ github.workspace }}/build
        shell: powershell
        run: cmake --build . --config Release -j3

      - name: Print versions
        working-directory: ${{ github.workspace }}/build
        shell: cmd
        run: .\app\Release\bergamot.exe --version

      - name: ccache epilog
        run: ccache.exe -sv
